# Generated by Django 6.0.6 on 2026-06-28 18:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('core', '0001_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoEstadoHistorico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('estado_logistico', models.CharField(choices=[('BORRADOR', 'Borrador'), ('CONFIRMADO', 'Confirmado'), ('PREPARACION', 'Preparacion'), ('DESPACHADO', 'Despachado'), ('ENTREGADO', 'Entregado'), ('ENTREGADO_PARCIAL', 'Entregado parcial'), ('FALLIDO', 'Fallido'), ('CANCELADO', 'Cancelado'), ('RESERVA_EXPIRADA', 'Reserva expirada')], max_length=20)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historico_estados', to='sales.pedido')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReservaInventario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=12)),
                ('estado', models.CharField(choices=[('RESERVADA', 'Reservada'), ('LIBERADA', 'Liberada'), ('CONSUMIDA', 'Consumida')], default='RESERVADA', max_length=10)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='sales.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='catalog.producto')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
