# Generated by Django 6.0.6 on 2026-06-28 06:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalReference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('source_system', models.CharField(max_length=50)),
                ('external_id', models.CharField(max_length=255)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
