# Generated by Django 6.0.6 on 2026-06-28 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalreference',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.tenant'),
        ),
        migrations.AddConstraint(
            model_name='externalreference',
            constraint=models.UniqueConstraint(fields=('tenant', 'source_system', 'external_id'), name='unique_external_reference_per_tenant'),
        ),
    ]
