# Generated by Django 6.0.6 on 2026-06-28 22:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionWhatsApp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('phone_number_id', models.CharField(max_length=50, unique=True)),
                ('business_account_id', models.CharField(max_length=50)),
                ('access_token', models.CharField(help_text='Token de usuario del sistema para ENVIAR mensajes. TODO: mover a un secret manager (GCP Secret Manager) antes de produccion.', max_length=512)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp', to='core.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventoWebhookWhatsApp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('external_id', models.CharField(help_text='wamid del mensaje de WhatsApp.', max_length=255)),
                ('payload', models.JSONField()),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
