# Generated by Django 6.0.6 on 2026-06-28 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_almacen_detalleordencompra_recepcioncompra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='almacen',
            name='es_cuarentena',
            field=models.BooleanField(default=False, help_text='Almacen virtual para mercaderia danada (BR-ABAST-01). No suma a stock vendible.'),
        ),
        migrations.AddField(
            model_name='detalleordencompra',
            name='cantidad_recibida',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Acumulado recibido hasta ahora (BR-ABAST-02/03). Actualizado por el service de recepcion.', max_digits=12),
        ),
    ]
