# Generated by Django 6.0.6 on 2026-06-28 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_almacen_es_cuarentena_and_more'),
        ('sales', '0002_pedidoestadohistorico_reservainventario'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinventario',
            name='reserva_inventario',
            field=models.ForeignKey(blank=True, help_text='Origen de una SALIDA real al despachar (BR-VENTA-04). Permite revertir el stock con precision si la entrega falla (BR-COB-03).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='sales.reservainventario'),
        ),
    ]
