# Generated by Django 6.0.6 on 2026-06-28 07:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=255)),
                ('sku', models.CharField(max_length=50)),
                ('unidad_base', models.CharField(default='UND', max_length=20)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Presentacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=50)),
                ('factor_conversion', models.DecimalField(decimal_places=4, max_digits=12)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.tenant')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presentaciones', to='catalog.producto')),
            ],
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.UniqueConstraint(fields=('tenant', 'sku'), name='unique_producto_sku_por_tenant'),
        ),
        migrations.AddConstraint(
            model_name='presentacion',
            constraint=models.UniqueConstraint(fields=('producto', 'nombre'), name='unique_presentacion_por_producto'),
        ),
    ]
