# Generated by Django 6.0.6 on 2026-06-28 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='costo_promedio',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Costo promedio ponderado (ADR-003). Se recalcula en cada recepcion de compra.', max_digits=12),
        ),
    ]
